# Demos/BlogBundle/Resources/config/admin.yml
services:
    sonata.admin.portfolio.post:
        class: Demos\BlogBundle\Admin\PostAdmin
        tags:
            - name: sonata.admin
              manager_type: orm
              group: "Portfolio"
              label: "Post"
        arguments:
            - ~
            - Demos\BlogBundle\Entity\Post
            - ~
        calls:
            - [ setTranslationDomain, [SonataAdminBundle]]

    sonata.admin.portfolio.category:
        class: Demos\BlogBundle\Admin\CategoryAdmin
        tags:
            - name: sonata.admin
              manager_type: orm
              group: "Portfolio"
              label: "Category"
        arguments:
            - ~
            - Demos\BlogBundle\Entity\Category
            - ~
        calls:
            - [ setTranslationDomain, [SonataAdminBundle]]

    sonata.admin.blogpost.post:
        class: Demos\BlogBundle\Admin\BlogPostAdmin
        tags:
            - name: sonata.admin
              manager_type: orm
              group: "Блог"
              label: "Blog Posts"
              label_catalogue: "DemosBlogBundle"
        arguments:
            - ~
            - Demos\BlogBundle\Entity\BlogPost
            - ~
        calls:
            - [ setTranslationDomain, [SonataAdminBundle]]

    sonata.admin.blogpost.category:
        class: Demos\BlogBundle\Admin\BlogCategoryAdmin
        tags:
            - name: sonata.admin
              manager_type: orm
              group: "Блог"
              label: "Blog Categories"
              label_catalogue: "DemosBlogBundle"
        arguments:
            - ~
            - Demos\BlogBundle\Entity\BlogCategory
            - ~
        calls:
            - [ setTranslationDomain, [SonataAdminBundle]]

    # Пробовал кастомизировать юзеров :
    sonata.admin.user:
        class: Demos\BlogBundle\Admin\UserAdmin
        tags:
            - name: sonata.admin
              manager_type: orm
              group: "Мои пользователи"
              label: "Мои пользователи"
              label_catalogue: "DemosBlogBundle"
        arguments:
            - ~
            - Demos\BlogBundle\Entity\User
            - 
        calls:
            - [ setTranslationDomain, [SonataAdminBundle]]

    # Пробовал кастомизировать группы юзеров :
    sonata.admin.user_group:
        class: Demos\BlogBundle\Admin\UserGroupAdmin
        tags:
            - name: sonata.admin
              manager_type: orm
              group: "Мои пользователи"
              label: "Мои группы"
              label_catalogue: "DemosBlogBundle"
        arguments:
            - ~
            - Demos\BlogBundle\Entity\Group
            - ~
        calls:
            - [ setTranslationDomain, [SonataAdminBundle]]
